config/routes.rb
Rails.application.routes.draw do
  resources :registers
  resources :enrolls
  resources :semesters
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root 'enrolls#new'

  resources :courses

  get '/semester' => 'semesters#index'

  get '/enrolls/edit' => 'enrolls#edit'

  get 'semesters/show' => 'semesters@show'

end

app/models/semester.rb
class Semester < ActiveRecord::Base
  before_save :status_check
  has_many :enrolls
  has_many :users, through: :enrolls

  validates_presence_of :sem_name, :status, :message => "Can't be empty"
  validates_uniqueness_of :sem_name, :message => "Already exists"

  STATUS = ['Done', 'Current', 'Due']

  scope :current, ->{ where(status: 'current')}

  protected

  def status_check
    if self.status_changed? && self.status == "Current"
      @prev = Semester.find_by_status("Current")
      if @prev != nil
        @prev.update_attribute(:status, "Done")
      end
    end
  end
end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_semester, only: [:show, :edit, :update, :destroy]
  before_filter :authorize_admin, only: [:new, :edit, :update, :destroy]


  # GET /semesters
  # GET /semesters.json
  def index
    @semesters = Semester.all
  end

  # GET /semesters/1
  # GET /semesters/1.json
  def show
  end

  # GET /semesters/new
  def new
    @semester = Semester.new
  end

  # GET /semesters/1/edit
  def edit
  end

  # POST /semesters
  # POST /semesters.json
  def create
    @semester = Semester.new(semester_params)

    respond_to do |format|
      if @semester.save

        format.html { redirect_to semesters_path, notice: 'Semester was successfully created.' }
        format.json { render :show, status: :created, location: @semester }
      else
        format.html { render :new }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /semesters/1
  # PATCH/PUT /semesters/1.json
  def update

    respond_to do |format|
      if @semester.update(semester_params)
        #status_check(@semester)
        format.html { redirect_to semesters_path, notice: 'Semester was successfully updated.' }
        format.json { render :show, status: :ok, location: @semester }
      else
        format.html { render :edit }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semesters/1
  # DELETE /semesters/1.json
  def destroy
    @semester.destroy
    respond_to do |format|
      format.html { redirect_to semesters_url, notice: 'Semester was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_semester
      @semester = Semester.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def semester_params
      #params.fetch(:semester, {})
      params.require(:semester).permit(:sem_name, :status, :maximum_credit)
    end
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/semesters/_form.html.erb
<%= form_for(@semester) do |f| %>
  <% if @semester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@semester.errors.count, "error") %> prohibited this semester from being saved:</h2>

      <ul>
      <% @semester.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="col-md-4 col-md-offset-4">

      <form>
        <fieldset class="form-group">
          <%= f.label :semester_name %>
          <%= f.text_field :sem_name, :placeholder => "Semester Name", class: 'form-control' %>
        </fieldset>

        <fieldset class="form-group">
          <div class="dropdown">
            <%= f.label :status %>
            <%= f.collection_select :status, Semester::STATUS, :to_s, :to_s, include_blank: true %>
          </div>

        </fieldset>

        <fieldset class="form-group">
          <%= f.label :maximum_credit %>
          <%= f.text_field :maximum_credit, :placeholder => "Maximum Credit", class: 'form-control' %>
        </fieldset>

        <%= f.submit "Create Semester", class: "btn btn-primary" %>


      </form>
    </div>
<% end %>

app/views/semesters/edit.html.erb
<h1>Editing Semester</h1>

<%= render 'form' %>

<%= link_to 'Show', @semester %> |
<%= link_to 'Back', semesters_path %>

app/views/semesters/index.html.erb
<div class="col-md-8 col-md-offset-2">

  <h2>Listing Courses</h2>

  <table class="table table-inverse table-bordered table-striped">
    <thead class="thead-inverse">
    <tr>
      <!--<th colspan="3"></th>-->
      <th>Semester</th>
      <th>Status</th>
      <th>Maximum Credit</th>
      <th></th>
    </tr>
    </thead>

  <tbody>
    <% @semesters.each do |semester| %>
  <tr>
    <td><%= semester.sem_name %></td>
    <td><%= semester.status %></td>
    <td><%= semester.maximum_credit %></td>

    <td class="list_action col-md-2">
      <%= link_to 'Show', semester %>
      <%= link_to 'Edit', edit_semester_path(semester)  %>
      <%= link_to 'Destroy', semester, method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<%= link_to 'New Semester', new_semester_path, class: "btn btn-primary"%>

app/views/semesters/new.html.erb
<h1>New Semester</h1>

<%= render 'form' %>

<%= link_to 'Back', semesters_path, class: "btn btn-primary" %>

app/views/semesters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_semester_path(@semester) %> |
<%= link_to 'Back', semesters_path %>