config/routes.rb
Rails.application.routes.draw do
  resources :registers
  resources :enrolls
  resources :semesters
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root 'enrolls#new'

  resources :courses

  get '/semester' => 'semesters#index'

  get '/enrolls/edit' => 'enrolls#edit'

  get 'semesters/show' => 'semesters@show'

end

app/models/register.rb
class Register < ActiveRecord::Base
  belongs_to :course
  belongs_to :enroll

  accepts_nested_attributes_for :course
  #accepts_nested_attributes_for :enroll




end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_register, only: [:show, :edit, :update, :destroy]

  # GET /registers
  # GET /registers.json
  def index
    @registers = Register.all

    @current_semester = Semester.find_by_status("Current")
    @completed_semesters = Semester.find_by_status("Done")
    @upcoming_semesters = Semester.find_by_status("Due")
    @current_enroll_id = @current_semester.enrolls.ids
    @completed_enroll_ids = @completed_semesters.enrolls.ids
    @upcoming_enroll_ids = @upcoming_semesters.enrolls.ids
  end

  # GET /registers/1
  # GET /registers/1.json
  def show
  end

  # GET /registers/new
  def new
    @register = Register.new
  end

  # GET /registers/1/edit
  def edit
  end

  # POST /registers
  # POST /registers.json
  def create
    @register = Register.new(register_params)

    respond_to do |format|
      if @register.save
        format.html { redirect_to @register, notice: 'Register was successfully created.' }
        format.json { render :show, status: :created, location: @register }
      else
        format.html { render :new }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /registers/1
  # PATCH/PUT /registers/1.json
  def update
    respond_to do |format|
      if @register.update(register_params)
        format.html { redirect_to @register, notice: 'Register was successfully updated.' }
        format.json { render :show, status: :ok, location: @register }
      else
        format.html { render :edit }
        format.json { render json: @register.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /registers/1
  # DELETE /registers/1.json
  def destroy
    @register.destroy
    respond_to do |format|
      format.html { redirect_to registers_url, notice: 'Register was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_register
      @register = Register.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def register_params
      params.require(:register).permit(:enroll, :course_id)
    end
end

app/helpers/registers_helper.rb
module RegistersHelper
end

app/views/registers/_form.html.erb
<%= form_for(@register) do |f| %>
  <% if @register.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@register.errors.count, "error") %> prohibited this register from being saved:</h2>

      <ul>
      <% @register.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :enroll %><br>
    <%= f.text_field :enroll %>
  </div>
  <div class="field">
    <%= f.label :course_id %><br>
    <%= f.text_field :course_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/registers/edit.html.erb
<h1>Editing Register</h1>

<%= render 'form' %>

<%= link_to 'Show', @register %> |
<%= link_to 'Back', registers_path %>

app/views/registers/index.html.erb
<h1>Listing Registers</h1>

<table>
  <thead>
    <tr>
      <th>Enroll</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @registers.each do |register| %>
      <tr>
        <td><%= link_to 'Show', register %></td>
        <td><%= link_to 'Edit', edit_register_path(register) %></td>
        <td><%= link_to 'Destroy', register, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Register', new_register_path, class: "btn btn-primary" %>

app/views/registers/new.html.erb
<h1>New Register</h1>

<%= render 'form' %>

<%= link_to 'Back', registers_path, class: "btn btn-primary" %>

app/views/registers/show.html.erb
<p>
  <strong>Enroll:</strong>
  <%= @register.enroll %>
</p>

<p>
  <strong>Course:</strong>
  <%= @register.course %>
</p>

<%= link_to 'Edit', edit_register_path(@register) %> |
<%= link_to 'Back', registers_path %>