config/routes.rb
Rails.application.routes.draw do
  resources :registers
  resources :enrolls
  resources :semesters
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root 'enrolls#new'

  resources :courses

  get '/semester' => 'semesters#index'

  get '/enrolls/edit' => 'enrolls#edit'

  get 'semesters/show' => 'semesters@show'

end

app/models/enroll.rb
class Enroll < ActiveRecord::Base
  before_create :semester_check
  before_save :credit_check

  belongs_to :user
  belongs_to :semester

  has_many :registers
  has_many :courses, through: :registers


  accepts_nested_attributes_for :registers
  accepts_nested_attributes_for :courses

  protected

  def semester_check
    begin
      current_semester = Semester.find_by_status("Current").id
      semester = Enroll.where(user_id: self.user_id, semester_id: current_semester)
      if semester.present?
        self.errors.add(:base, 'Already Registered!!')
        return false

      else
        return true

      end
    end
  end

  def credit_check
    total = 0
    course_ids = self.course_ids
    courses = Course.where(id: course_ids)
    courses.each do |course|
      credit = course.credit
      total += credit
    end
    semester_id = self.semester_id
    @maximum_credit = Semester.find_by(semester_id).maximum_credit
    #@maximum_credit = 2.00
    if total > @maximum_credit
      self.errors.add(:base, 'Maximum Credit Exceeded!!')
      return false
    else
      return true
    end
  end
end

app/controllers/enrolls_controller.rb
class EnrollsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_enroll, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js

  # GET /enrolls
  # GET /enrolls.json
  def index
    @enrolls = Enroll.all
  end

  # GET /enrolls/1
  # GET /enrolls/1.json
  def show
    @enroll = Enroll.find(params[:id])
  end

  # GET /enrolls/new
  def new
    @user = current_user
    @semester = Semester.find_by_status("Current")
    @maximum_credit =  @semester.maximum_credit.present? ? @semester.maximum_credit : nil
    @courses =  Course.where("semester = ?", @semester.sem_name)
    @enroll = Enroll.new(user_id: @user.id, semester_id: @semester.id)
    @courses.each do |course|
      @enroll.registers.new(course_id: course.id)
    end
  end

  # GET /enrolls/1/edit
  def edit
    @user = current_user
    @semester = Semester.find_by_status("Current")
    @maximum_credit = @semester.maximum_credit
    @courses =  Course.where("semester = ?", @semester.sem_name)
  end

  # POST /enrolls
  # POST /enrolls.json
  def create
    @enroll = Enroll.new(enroll_params)

    # params[:enroll][:course_ids].each do |c_id|
    #   @enroll.registers.new(course_id: c_id) if c_id.present?
    # end

    respond_to do |format|
      if @enroll.save
        # params[:course_attributes].each do |course|
        #   @enroll.registers.create(course_id: course['course_id'], enroll_id: @enroll.id)
        # end
        format.html { redirect_to @enroll, notice: 'Enroll was successfully created.' }
        format.js { }
        format.json { render :show, status: :created, location: @enroll }
      else
        @user = current_user
        @semester = Semester.find_by_status("Current")
        @courses =  Course.where("semester = ?", @semester.sem_name)
        @courses.each do |course|
          @enroll.registers.new(course_id: course.id)
        end
        format.html { render :edit }
        format.json { render new_enroll_path @enroll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enrolls/1
  # PATCH/PUT /enrolls/1.json
  def update
    @user = current_user
    @semester = Semester.find_by_status("Current")
    @maximum_credit = @semester.maximum_credit
    @courses =  Course.where("semester = ?", @semester.sem_name)
    respond_to do |format|
      if @enroll.update(enroll_params)
        format.html { redirect_to @enroll, notice: 'Enroll was successfully updated.' }
        format.json { render :show, status: :ok, location: @enroll }
      else
        format.html { render :edit }
        format.json { render json: @enroll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enrolls/1
  # DELETE /enrolls/1.json
  def destroy
    @enroll.destroy
    respond_to do |format|
      format.html { redirect_to enrolls_url, notice: 'Enroll was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enroll
      @enroll = Enroll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enroll_params
      #params.require(:enroll).permit(:user_id, :course_id, :semester_id, :user_attributes, :semester_attributes,  registers_attributes: [course_attributes:[]])
      params.require(:enroll).permit(:user_id, :semester_id, :status, course_ids:[])
    end
end

app/helpers/enrolls_helper.rb
module EnrollsHelper
end

app/views/enrolls/_form.html.erb
<%= form_for(@enroll) do |f| %>
  <% if @enroll.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enroll.errors.count, "error") %> prohibited this enroll from being saved:</h2>

      <ul>
      <% @enroll.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-inline col-md-6 col-md-offset-4">

      <label>
        Semester:
        <%= f.object.semester.sem_name %>
        <%= f.hidden_field :semester_id %>
      </label>

      <label>
        Student:
        <%= f.object.user.first_name %>
        <%= f.hidden_field :user_id %>
      </label>

      <label>
        Maximum Credit: <%= @maximum_credit %>
      </label>

      <label>
        <% f.object.semester.status %>
        <%= f.hidden_field :status %>
      </label>
    </div>

    <div class="col-md-6 col-md-offset-4">

      <%= collection_check_boxes(:enroll, :course_ids, @courses, :id, :course_title_with_credit) do |c| %>
          <div class="collection-check-box">
            <%= c.check_box(:"data-credit" => c.object.credit) %>
            <%= c.label%>
          </div>
      <% end %>

    </div>
  <div class="col-md-4 col-md-offset-4">
    <%= f.submit %>
  </div>

<% end %>

app/views/enrolls/edit.html.erb
<h1>Editing Enroll</h1>

<%= render 'form' %>

<%= link_to 'Show', @enroll, class: "btn btn-primary"  %> |
<%= link_to 'Back', enrolls_path, class: "btn btn-primary"  %>

app/views/enrolls/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Enrolls</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Semester</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @enrolls.each do |enroll| %>
      <tr>
        <td><%= enroll.user.first_name %></td>
        <td><%= enroll.semester.sem_name %></td>
        <td><%= enroll.semester.status %></td>
        <td><%= link_to 'Show', enroll %></td>
        <td><%= link_to 'Edit', edit_enroll_path(enroll) %></td>
        <td><%= link_to 'Destroy', enroll, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Enroll', new_enroll_path, class: "btn btn-primary"  %>

app/views/enrolls/new.html.erb
<h1  class="new text-center">New Enroll <%= current_user.roll %></h1>

<div class="col-md-6 col-md-offset-4 alert alert-danger" id="credit-form" style="display:none;">
  <h3>Total credit exceeded!!</h3>
</div>

<%= render 'form' %>

<div class="col-md-6 col-md-offset-4" id="display-credit">
</div>

<%= link_to 'Back', enrolls_path, class: "btn btn-primary"  %>

app/views/enrolls/show.html.erb
<p>
  <strong>User:</strong>
  <%= @enroll.user.first_name %>
</p>

<p>
  <strong>Courses:</strong>
  <% @enroll.registers.each do |r| %>
   <%= r.course.course_title %> |
  <% end %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @enroll.semester.sem_name %>
</p>

<%= link_to 'Edit', edit_enroll_path(@enroll), class: "btn btn-primary" %> |
<%= link_to 'Back', enrolls_path, class: "btn btn-primary" %>